### ISSUE TITLE
No DateTimeOriginal tag found

### ISSUE THREAD

**Issue by ManChrys** [gvellut/gpx2exif#2]
Hello,

i would like to ask i f i want to add a gpx file to a folder, which has images, the images should have only the DateTimeOriginal tag ?

because i have extracted images(frames) from a video and they dont have metadata, so i want to add gps data through gpx but i have the following error.

> D:\Labpano_tests>gpx2exif image GPS.gpx D:\Labpano_tests\1_fps
Parsing time shift...
Time shift: 0h0m0s
Parsing tolerance...
Tolerance: 10s
Parsing GPX...
GPX time range: 2022-06-22 07:25:39.046596+00:00 => 2022-06-22 07:31:11.042231+00:00
Synching EXIF GPS to GPX...
Cannot compute position for file GPS_frame00000 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00000.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00001 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00001.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00002 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00002.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00003 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00003.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00004 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00004.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00005 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00005.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00006 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00006.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00007 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00007.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00008 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00008.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00009 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00009.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00010 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00010.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00011 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00011.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00012 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00012.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00013 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00013.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00014 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00014.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00015 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00015.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00016 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00016.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00017 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00017.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00018 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00018.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00019 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00019.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00020 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00020.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00021 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00021.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00022 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00022.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00023 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00023.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00024 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00024.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00025 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00025.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00026 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00026.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00027 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00027.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00028 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00028.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00029 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00029.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00030 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00030.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00031 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00031.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00032 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00032.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00033 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00033.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00034 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00034.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00035 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00035.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00036 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00036.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00037 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00037.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00038 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00038.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00039 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00039.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00040 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00040.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00041 - Copy.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00041.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00042.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00043.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00044.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00045.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00046.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00047.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00048.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00049.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00050.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00051.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00052.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00053.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00054.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00055.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00056.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00057.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00058.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00059.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00060.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00061.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00062.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00063.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00064.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00065.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00066.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00067.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00068.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00069.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00070.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00071.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00072.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00073.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00074.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00075.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00076.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00077.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00078.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00079.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00080.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00081.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00082.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00083.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00084.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00085.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00086.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00087.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00088.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00089.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00090.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00091.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00092.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00093.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00094.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00095.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00096.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00097.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00098.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00099.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00100.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00101.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00102.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00103.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00104.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00105.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00106.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00107.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00108.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00109.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00110.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00111.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00112.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00113.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00114.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00115.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00116.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00117.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00118.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00119.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00120.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00121.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00122.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00123.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00124.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00125.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00126.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00127.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00128.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00129.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00130.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00131.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00132.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00133.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00134.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00135.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00136.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00137.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00138.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00139.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00140.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00141.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00142.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00143.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00144.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00145.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00146.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00147.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00148.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00149.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00150.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00151.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00152.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00153.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00154.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00155.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00156.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00157.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00158.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00159.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00160.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00161.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00162.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00163.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00164.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00165.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00166.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00167.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00168.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00169.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00170.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00171.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00172.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00173.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00174.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00175.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00176.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00177.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00178.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00179.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00180.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00181.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00182.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00183.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00184.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00185.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00186.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00187.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00188.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00189.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00190.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00191.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00192.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00193.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00194.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00195.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00196.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00197.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00198.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00199.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00200.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00201.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00202.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00203.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00204.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00205.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00206.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00207.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00208.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00209.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00210.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00211.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00212.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00213.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00214.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00215.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00216.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00217.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00218.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00219.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00220.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00221.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00222.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00223.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00224.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00225.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00226.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00227.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00228.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00229.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00230.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00231.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00232.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00233.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00234.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00235.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00236.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00237.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00238.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00239.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00240.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00241.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00242.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00243.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00244.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00245.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00246.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00247.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00248.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00249.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00250.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00251.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00252.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00253.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00254.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00255.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00256.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00257.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00258.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00259.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00260.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00261.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00262.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00263.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00264.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00265.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00266.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00267.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00268.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00269.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00270.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00271.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00272.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00273.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00274.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00275.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00276.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00277.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00278.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00279.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00280.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00281.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00282.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00283.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00284.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00285.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00286.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00287.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00288.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00289.jpg (No DateTimeOriginal tag found)
Cannot compute position for file GPS_frame00290.jpg (No DateTimeOriginal tag found)

**Comment by gvellut** [comment]
Yes, the images should have the DateTimeOriginal EXIF tag.

Do your images have that tag? If you have extracted the frames from the video with no other processing, it is unlikely the tag is there though. I you want, you can send one of the images so I can check. 

If not, you will have to add it first (using piexif and Python for example).

**Comment by gvellut** [comment]
OK. So I guess you will have to add it yourself. 

Did you extract the images at a constant interval (say 1 frame every second) ? If you know the time of the beginning of the video (possibly the Date Created of the original video file according to the file system), then the first frame will be at that `time_beginning` and the times of the following images will be incremented by `frame_interval` (1s for example). Note that the Date Created in the file system can sometimes be unreliable if the file is copied between devices but you can check if it makes sense in your case or check the time of the original video on the device.

Then you can use Python + piexif to loop through the images and add the DateTimeOriginal EXIF tag. Then, finally, use gpx2exif to add the GPS info.

Note that in the `gpx2exif `command, you should add an offset using `--delta-tz`, corresponding to the timezone / offset from GMT if the times in the video is in local time (for Greece, I think it should be "-3h" if during summer time, so `--delta-tz -3h`). If the device that recorded the GPS and the device that recorded the video are different, you may also need to add a `--delta` offset (to make the time in the GPS match with the time of the images).

**Comment by ManChrys** [comment]
wow amazing response!!!! thanks a lot my friend.

yeah i cut frames every 1 sec. The video has all the metadata and the time of the video is correct, so i'll try to give the datetime to the rest of the frames.

I import metadata to the images with the exiftool
`exiftool -csv="csv_path/data.csv" "images_path"`

but i want to try your project too, so i'll follow your instructions.

Thanks again my friend.
